spring:
    datasource:
        url: ${SUPABASE_JDBC_URL}
        username: ${SUPABASE_DB_USERNAME}
        password: ${SUPABASE_DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: update
        open-in-view: false

springdoc:
    api-docs:
        path: /v3/api-docs
    swagger-ui:
        path: /swagger-ui.html
